services:
  web:
    build: .
    container_name: node-api
    restart: unless-stopped
    volumes:
      - ./images:/app/images
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true